[theme]
base = "light"
primaryColor = "#000000"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f9fafb"
textColor = "#000000"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
